apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: goflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-discovery
  namespace: goflow
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-discovery
  namespace: goflow
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: goflow
roleRef:
  kind: Role
  name: prometheus-discovery
  apiGroup: rbac.authorization.k8s.io