apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: goflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin

            - name: GF_SMTP_ENABLED
              value: "true"

            - name: GF_SMTP_HOST
              value: "smtp.gmail.com:587"

            - name: GF_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: username

            - name: GF_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: password

            - name: GF_SMTP_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: username

            - name: GF_SMTP_STARTTLS_POLICY
              value: "MandatoryStartTLS"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:

            # Existing persistent Grafana storage
            - name: grafana-storage
              mountPath: /var/lib/grafana

            # Dashboard JSON
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/dashboards

            # Dashboard provisioning configuration
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards

            - name: grafana-alerting
              mountPath: /etc/grafana/provisioning/alerting

      volumes:

        # Existing PVC — DO NOT REMOVE
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage

        # Dashboard ConfigMap
        - name: grafana-dashboard
          configMap:
            name: goflow-grafana-dashboard

        # Provider ConfigMap
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        #alerts for grafana

        - name: grafana-alerting
          configMap:
            name: grafana-alerting-rules
