apiVersion: v1
data:
  goflow-alerts.yml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: GoFlow ALERTS
        folder: GoFlow
        interval: 30s
        rules:
          - uid: bfw5w0twgrqpsf
            title: GoFlow - Queue Backlog
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: bfw5t7xkd5t6od
                model:
                  editorMode: code
                  expr: sum(goflow_queue_length)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                queryType: expression
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 10
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: empty
          - uid: ffw5w7ehnjv9cf
            title: GoFlow - Task Failures
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: bfw5t7xkd5t6od
                model:
                  editorMode: code
                  expr: sum(increase(goflow_tasks_failed_total[5m]))
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                queryType: expression
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: empty
          - uid: bfw5wctbyfabkc
            title: GoFlow - Retry Storm
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: bfw5t7xkd5t6od
                model:
                  editorMode: code
                  expr: sum(increase(goflow_task_retries_total[5m]))
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                queryType: expression
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: empty
          - uid: efw5wgco32yv4b
            title: GoFlow - Worker Saturation
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: bfw5t7xkd5t6od
                model:
                  editorMode: code
                  expr: sum(goflow_workers_busy)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                queryType: expression
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 2
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: empty
          - uid: ffw5wks10do8wc
            title: GoFlow - High CPU
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: bfw5t7xkd5t6od
                model:
                  editorMode: code
                  expr: sum(rate(process_cpu_seconds_total[5m]))
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                queryType: expression
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 5m
            isPaused: false
            notification_settings:
              receiver: empty
          - uid: dfw5wpqckffgge
            title: GoFlow - High Memory
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: bfw5t7xkd5t6od
                model:
                  editorMode: code
                  expr: sum(process_resident_memory_bytes)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                queryType: expression
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 300
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: empty
kind: ConfigMap
metadata:
  name: grafana-alerting-rules
  namespace: goflow
