apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Shauryan10/GoFlow.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: goflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true