apiVersion: apps/v1
kind: Deployment
metadata:
  name: goflow
  namespace: goflow
spec:
  replicas: 1

  selector:
    matchLabels:
      app: goflow

  template:
    metadata:
      labels:
        app: goflow

    spec:
      automountServiceAccountToken: false

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: goflow

          image: ghcr.io/shauryan10/goflow:latest
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8080
              protocol: TCP

          envFrom:
            - configMapRef:
                name: goflow-config

            - secretRef:
                name: goflow-db-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"